#!/bin/bash -e

site_JULIA_PKGDIR="`julia -e 'println(dirname(last(LOAD_PATH)))'`"
# echo "DEBUG: site_JULIA_PKGDIR=\"${site_JULIA_PKGDIR}\"." >&2

site_pkgdir=`JULIA_PKGDIR="${site_JULIA_PKGDIR}" julia -e julia -e 'println(Pkg.dir())'`
echo "INFO: Site-wide Julia package directory: \"${site_pkgdir}\"." >&2

user_pkgdir=`julia -e 'println(Pkg.dir())'`
echo "INFO: User Julia package directory: \"${user_pkgdir}\"." >&2

mkdir -p "${user_pkgdir}"
ln -s "${site_pkgdir}"/* "${user_pkgdir}/"
rm "${user_pkgdir}/REQUIRE"
cp -a "${site_pkgdir}/REQUIRE" "${user_pkgdir}/"

site_LOAD_CACHE_PATH=`JULIA_PKGDIR="${site_JULIA_PKGDIR}" julia -e 'println(Base.LOAD_CACHE_PATH[1])'`
# echo "DEBUG: site_LOAD_CACHE_PATH=\"${site_LOAD_CACHE_PATH}\"." >&2

user_LOAD_CACHE_PATH=`julia -e 'println(Base.LOAD_CACHE_PATH[1])'`
# echo "DEBUG: user_LOAD_CACHE_PATH=\"${user_LOAD_CACHE_PATH}\"." >&2

mkdir -p "${user_LOAD_CACHE_PATH}"
ln -s "${site_LOAD_CACHE_PATH}"/* "${user_LOAD_CACHE_PATH}/"
