#!/bin/bash -e

preinst_pkgdir=`JULIA_PKGDIR="/dev/null/nosuchdir" julia -e julia -e 'println(Pkg.dir())'`
user_pkgdir=`JULIA_FORCE_USER_PKGDIR="1" julia -e 'println(Pkg.dir())'`

preinst_LOAD_CACHE_PATH=`JULIA_PKGDIR="/dev/null/nosuchdir" julia -e 'println(Base.LOAD_CACHE_PATH[1])'`
user_LOAD_CACHE_PATH=`JULIA_FORCE_USER_PKGDIR="1" julia -e 'println(Base.LOAD_CACHE_PATH[1])'`


cat >&2 <<EOF
Creating user Julia package directory

	"${user_pkgdir}"

containing symbolic links to

	"${preinst_pkgdir}"

EOF

mkdir -p `dirname "${user_pkgdir}"`
mkdir "${user_pkgdir}"
ln -s "${preinst_pkgdir}"/* "${user_pkgdir}/"
rm "${user_pkgdir}/REQUIRE"
cp -a "${preinst_pkgdir}/REQUIRE" "${user_pkgdir}/"


cat >&2 <<EOF
Creating user Julia precompilation cache directory

	"${user_LOAD_CACHE_PATH}"

containing symbolic links to

	"${preinst_LOAD_CACHE_PATH}"

EOF

mkdir -p `dirname "${user_LOAD_CACHE_PATH}"`
mkdir "${user_LOAD_CACHE_PATH}"
ln -s "${preinst_LOAD_CACHE_PATH}"/* "${user_LOAD_CACHE_PATH}/"
